[project]
name = "python-logging-loki"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[all]>=0.115.11",
    "python-json-logger>=3.3.0",
]

[tool.uv]
dev-dependencies = [
    "ruff>=0.9.10",
]
